################ German language ##################
[de]
languageName = "Deutsch"
languageCode = "de-DE"
contentDir = "content/de"
weight = 1

################ Czech language ##################
[cz]
languageName = "Čeština"
languageCode = "cz"
contentDir = "content/cz"
weight = 2

################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 3