############# English navigation ##############

# main menu
[[main]]
weight = 1
name = "Touren"
url = "tour/"

[[main]]
weight = 2
name = "Blog"
url = "blog/"

[[main]]
weight = 3
name = "Info"
url = "about"



# footer menu
[[footer]]
name = "Impressum"
url = "impressum"
weight = 1

[[footer]]
name = "Datenschutz"
url = "datenschutz"
weight = 2