############# English navigation ##############

# main menu
[[main]]
name = "Start"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Blog"
url = "blog/"

[[main]]
weight = 3
name = "Organisatoren"
url = "organisatoren/"



# footer menu
[[footer]]
name = "Impressum"
url = "impressum/"
weight = 1

[[footer]]
name = "Datenschutz"
url = "datenschutz/"
weight = 2