############# English navigation ##############

# main menu
#[[main]]
#name = "Home"
#url = "/"
#weight = 1

#[[main]]
#weight = 2
#name = "Blog"
#url = "blog/"


# footer menu
[[footer]]
name = "Imprint"
url = "../impressum"
weight = 1

[[footer]]
name = "Data Protection"
url = "../datenschutz"
weight = 2