############# English navigation ##############

# main menu
[[main]]
name = "Začátek"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Blog"
url = "blog/"

[[main]]
weight = 3
name = "Organizátoři"
url = "authors/"



# footer menu
[[footer]]
name = "Otisk"
url = "imprint/"
weight = 1

[[footer]]
name = "Ochrana dat"
url = "data-protection/"
weight = 2