############# English navigation ##############

# main menu
[[main]]
name = "Start"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Blog"
url = "blog/"



# footer menu
[[footer]]
name = "Impressum"
url = "impressum"
weight = 1

[[footer]]
name = "Datenschutz"
url = "datenschutz"
weight = 2